development:
  metadata_adapter: composite_persister
  storage_adapter: disk

staging:
  metadata_adapter: composite_persister
  storage_adapter: disk

test:
  metadata_adapter: composite_persister
  storage_adapter: test_disk

production:
  metadata_adapter: composite_persister
  storage_adapter: disk
